version: "3.8"
services:
    telegram-bot:
        build: .
        container_name: telegram-bot
        restart: unless-stopped
        volumes:
            - ./backups:/app/backups
        env_file:
            - .env # Baca environment variable dari file .env
